version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prova
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 7878:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app:
    build: .
    container_name: PROVA
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/prova
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - 8000:8000
    depends_on:
      - postgres
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  pgdata:
  pgadmin_data:
